### PR TITLE
[feat] remove the need to manually add totalNumber

### PR DESCRIPTION
**Pull request by mcclowes**

### CODE REVIEW

**Comment by dronsfield** [comment]
cool idea, I just wonder how likely it is that the hash is going to persist across deploys

**Comment by mcclowes** [comment]
Yeah it's very possible. Annoyingly there's no more specific classes or anything either

**Comment by mcclowes** [comment]
But yeah, this sped up me capturing my playlists quite a lot, so thought I'd share

**Comment by dronsfield** [comment]
and I guess even if the hash does change frequently - this update doesn't _stop_ anyone manually changing the number

awesome, thanks for contributing!

**Pull request merged**
